### ISSUE TITLE
Could you please provide a simplified version of the radar and lidar raw data？

### ISSUE THREAD

**Issue by liuzhaoo** [akarsh-prabhakara/RadarHD#1]
Very pleasantly surprised to find research related to millimeter wave radar, I am very interested in your work. Thank you very much for providing a complete  raw data set. I am a researcher from China. As we all know, it is very difficult for us to download the data set on Google Cloud Disk, especially when the data volume is relatively large（77G）. Can you provide a smaller version of the dataset (no more than 5G), I would like to know the complete process of dataset processing. You can also upload to Google Cloud Disk in the same way. Thank you so much

**Comment by akarsh-prabhakara** [comment]
Thanks for asking! Surely, will notify you when I update it

**Comment by liuzhaoo** [comment]
That's great! Thank you very much!

**Comment by liuzhaoo** [comment]
Hi，is there any update？

**Comment by akarsh-prabhakara** [comment]
The new readme should have link to a smaller dataset that you requested for.
